Resources:
  FeedbackSentimentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FeedbackSentiment
      AttributeDefinitions:
        - AttributeName: processingDate
          AttributeType: S
        - AttributeName: feedbackId
          AttributeType: S
      KeySchema:
        - AttributeName: processingDate
          KeyType: HASH
        - AttributeName: feedbackId
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
